#ifndef _MTK_VIDEOAINR_ERRCODE_H
#define _MTK_VIDEOAINR_ERRCODE_H

#include "MTKVideoAINRType.h"

typedef MINT32 MRESULT;

#define S_VIDEOAINR_OK                  (0x0000)
#define E_VIDEOAINR_NEED_OVERRIDE       (0x0001)
#define E_VIDEOAINR_WRONG_FEATURE_ID    (0x0002)
#define E_VIDEOAINR_NULL_INPUT          (0x0003)
#define E_VIDEOAINR_WRONG_INPUT			(0x0004)
#define E_VIDEOAINR_NOT_ENOUGH_MEM      (0x0005)
#define E_VIDEOAINR_INVALID_TILE_NUM    (0x0006)
#define E_VIDEOAINR_MDLA_INIT_FAIL		(0x0007)
#define E_VIDEOAINR_NULL_NVRAM			(0x0008)
#define E_VIDEOAINR_WRONG_RESOLUTION	(0x0009)
#define E_VIDEOAINR_VPU_INIT_FAIL		(0x0010)

#define E_VIDEOAINR_ERR                 (0x0100)

#endif
